/**
 * 语言代码映射
 * 参考 rustplusplus 的实现
 * 支持中英文语言名称
 */

const Languages = {
  // 常用语言（中文名）
  "中文": "zh",
  "简体中文": "zh",
  "繁体中文": "zh-TW",
  "英语": "en",
  "英文": "en",
  "日语": "ja",
  "日文": "ja",
  "韩语": "ko",
  "韩文": "ko",
  "法语": "fr",
  "法文": "fr",
  "德语": "de",
  "德文": "de",
  "西班牙语": "es",
  "西语": "es",
  "俄语": "ru",
  "俄文": "ru",
  "葡萄牙语": "pt",
  "葡语": "pt",
  "意大利语": "it",
  "意语": "it",
  "阿拉伯语": "ar",
  "阿语": "ar",
  "越南语": "vi",
  "越语": "vi",
  "泰语": "th",
  "印尼语": "id",
  "马来语": "ms",
  "菲律宾语": "tl",
  "印地语": "hi",
  "土耳其语": "tr",
  "波兰语": "pl",
  "荷兰语": "nl",
  "瑞典语": "sv",
  "挪威语": "no",
  "丹麦语": "da",
  "芬兰语": "fi",
  "希腊语": "el",
  "捷克语": "cs",
  "匈牙利语": "hu",
  "罗马尼亚语": "ro",
  "乌克兰语": "uk",
  "希伯来语": "he",

  // 英文语言名称
  "afar": "aa",
  "abkhazian": "ab",
  "afrikaans": "af",
  "akan": "ak",
  "albanian": "sq",
  "amharic": "am",
  "arabic": "ar",
  "aragonese": "an",
  "armenian": "hy",
  "assamese": "as",
  "avaric": "av",
  "avestan": "ae",
  "aymara": "ay",
  "azerbaijani": "az",
  "bashkir": "ba",
  "bambara": "bm",
  "basque": "eu",
  "belarusian": "be",
  "bengali": "bn",
  "bihari languages": "bh",
  "bislama": "bi",
  "tibetan": "bo",
  "bosnian": "bs",
  "breton": "br",
  "bulgarian": "bg",
  "burmese": "my",
  "catalan": "ca",
  "valencian": "ca",
  "czech": "cs",
  "chamorro": "ch",
  "chechen": "ce",
  "chinese": "zh",
  "church slavic": "cu",
  "old slavonic": "cu",
  "church slavonic": "cu",
  "old bulgarian": "cu",
  "old church slavonic": "cu",
  "chuvash": "cv",
  "cornish": "kw",
  "corsican": "co",
  "cree": "cr",
  "welsh": "cy",
  "danish": "da",
  "german": "de",
  "divehi": "dv",
  "dhivehi": "dv",
  "maldivian": "dv",
  "dutch": "nl",
  "flemish": "nl",
  "dzongkha": "dz",
  "greek": "el",
  "english": "en",
  "esperanto": "eo",
  "estonian": "et",
  "ewe": "ee",
  "faroese": "fo",
  "persian": "fa",
  "fijian": "fj",
  "finnish": "fi",
  "french": "fr",
  "western frisian": "fy",
  "fulah": "ff",
  "georgian": "ka",
  "gaelic": "gd",
  "scottish gaelic": "gd",
  "irish": "ga",
  "galician": "gl",
  "manx": "gv",
  "guarani": "gn",
  "gujarati": "gu",
  "haitian": "ht",
  "haitian creole": "ht",
  "hausa": "ha",
  "hebrew": "he",
  "herero": "hz",
  "hindi": "hi",
  "hiri motu": "ho",
  "croatian": "hr",
  "hungarian": "hu",
  "igbo": "ig",
  "icelandic": "is",
  "ido": "io",
  "sichuan yi": "ii",
  "nuosu": "ii",
  "inuktitut": "iu",
  "interlingue": "ie",
  "occidental": "ie",
  "interlingua": "ia",
  "indonesian": "id",
  "inupiaq": "ik",
  "italian": "it",
  "javanese": "jv",
  "japanese": "ja",
  "kalaallisut": "kl",
  "greenlandic": "kl",
  "kannada": "kn",
  "kashmiri": "ks",
  "kanuri": "kr",
  "kazakh": "kk",
  "central khmer": "km",
  "kikuyu": "ki",
  "gikuyu": "ki",
  "kinyarwanda": "rw",
  "kirghiz": "ky",
  "kyrgyz": "ky",
  "komi": "kv",
  "kongo": "kg",
  "korean": "ko",
  "kuanyama": "kj",
  "kwanyama": "kj",
  "kurdish": "ku",
  "lao": "lo",
  "latin": "la",
  "latvian": "lv",
  "limburgan": "li",
  "limburger": "li",
  "limburgish": "li",
  "lingala": "ln",
  "lithuanian": "lt",
  "luxembourgish": "lb",
  "letzeburgesch": "lb",
  "luba-katanga": "lu",
  "ganda": "lg",
  "macedonian": "mk",
  "marshallese": "mh",
  "malayalam": "ml",
  "maori": "mi",
  "marathi": "mr",
  "malay": "ms",
  "malagasy": "mg",
  "maltese": "mt",
  "mongolian": "mn",
  "nauru": "na",
  "navajo": "nv",
  "navaho": "nv",
  "ndebele, south": "nr",
  "south ndebele": "nr",
  "ndebele, north": "nd",
  "north ndebele": "nd",
  "ndonga": "ng",
  "nepali": "ne",
  "norwegian nynorsk": "nn",
  "nynorsk, norwegian": "nn",
  "norwegian bokmal": "nb",
  "bokmal, norwegian": "nb",
  "norwegian": "no",
  "chichewa": "ny",
  "chewa": "ny",
  "nyanja": "ny",
  "occitan": "oc",
  "ojibwa": "oj",
  "oriya": "or",
  "oromo": "om",
  "ossetian": "os",
  "ossetic": "os",
  "panjabi": "pa",
  "punjabi": "pa",
  "pali": "pi",
  "polish": "pl",
  "portuguese": "pt",
  "pushto": "ps",
  "pashto": "ps",
  "quechua": "qu",
  "romansh": "rm",
  "romanian": "ro",
  "moldavian": "ro",
  "moldovan": "ro",
  "rundi": "rn",
  "russian": "ru",
  "sango": "sg",
  "sanskrit": "sa",
  "sinhala": "si",
  "sinhalese": "si",
  "slovak": "sk",
  "slovenian": "sl",
  "northern sami": "se",
  "samoan": "sm",
  "shona": "sn",
  "sindhi": "sd",
  "somali": "so",
  "sotho, southern": "st",
  "spanish": "es",
  "castilian": "es",
  "sardinian": "sc",
  "serbian": "sr",
  "swati": "ss",
  "sundanese": "su",
  "swahili": "sw",
  "swedish": "sv",
  "tahitian": "ty",
  "tamil": "ta",
  "tatar": "tt",
  "telugu": "te",
  "tajik": "tg",
  "tagalog": "tl",
  "thai": "th",
  "tigrinya": "ti",
  "tonga": "to",
  "tswana": "tn",
  "tsonga": "ts",
  "turkmen": "tk",
  "turkish": "tr",
  "twi": "tw",
  "uighur": "ug",
  "uyghur": "ug",
  "ukrainian": "uk",
  "urdu": "ur",
  "uzbek": "uz",
  "venda": "ve",
  "vietnamese": "vi",
  "volapuk": "vo",
  "walloon": "wa",
  "wolof": "wo",
  "xhosa": "xh",
  "yiddish": "yi",
  "yoruba": "yo",
  "zhuang": "za",
  "chuang": "za",
  "zulu": "zu"
};

/**
 * 获取语言代码
 * @param {string} languageName - 语言名称（支持中英文）
 * @returns {string|null} - ISO 639-1 语言代码，找不到返回 null
 */
export function getLanguageCode(languageName) {
  if (!languageName) return null;

  const normalized = languageName.toLowerCase().trim();

  // 如果输入的已经是语言代码（2-5个字符），直接返回
  if (/^[a-z]{2,5}(-[a-z]{2,5})?$/i.test(normalized)) {
    return normalized;
  }

  return Languages[normalized] || null;
}

/**
 * 获取所有支持的语言列表
 * @returns {string[]} - 语言名称数组
 */
export function getSupportedLanguages() {
  return Object.keys(Languages);
}

/**
 * 检查语言是否支持
 * @param {string} languageName - 语言名称
 * @returns {boolean}
 */
export function isLanguageSupported(languageName) {
  return getLanguageCode(languageName) !== null;
}

export default Languages;
